better failure messages

diff --git a/bin/mgmt b/bin/mgmt
--- a/bin/mgmt
+++ b/bin/mgmt
@@ -261,7 +261,7 @@ link(){
                     min) FLAGS="-Wno-deprecated";;
                     all) FLAGS="$PARSEC_BASE_FLAGS_ALL -Wno-deprecated";;
                 esac
-                g++ $FLAGS ${bench}.s -o $bench||error "compilation failed"
+                g++ $FLAGS ${bench}.s -o $bench||error "linking failed"
                 ;;
             swaptions)
                 SWAP_FLAGS="-pthread  -DENABLE_THREADS"
@@ -269,7 +269,7 @@ link(){
                     min) FLAGS="$SWAP_FLAGS";;
                     all) FLAGS="$PARSEC_BASE_FLAGS_ALL $SWAP_FLAGS";;
                 esac
-                g++ $FLAGS ${bench}.s -o $bench||error "compilation failed"
+                g++ $FLAGS ${bench}.s -o $bench||error "linking failed"
                 ;;
 
             ## SPEC
@@ -278,13 +278,13 @@ link(){
                     min) FLAGS="";;
                     all) FLAGS="-O3";;
                 esac
-                gcc $FLAGS ${bench}.s -o $bench||error "compilation failed";;
+                gcc $FLAGS ${bench}.s -o $bench||error "linking failed";;
             h264ref)
                 case $FLAGS in
                     min) FLAGS="-lm ";;
                     all) FLAGS="-lm -O3";;
                 esac
-                gcc $FLAGS ${bench}.s -o $bench||error "compilation failed";;
+                gcc $FLAGS ${bench}.s -o $bench||error "linking failed";;
             *) error "linking not implemented for $bench"
         esac
         popd>/dev/null
