updated x264-test to provide a perf option

diff --git a/bin/x264-test b/bin/x264-test
--- a/bin/x264-test
+++ b/bin/x264-test
@@ -2,24 +2,21 @@
 #
 # Usage: x264-test EXECUTABLE [OPTIONS...]
 #
+# Run the given executable comparing its output against known good
+# output.  Return the total difference between the outputs.
+#
 # EXECUTABLE -- executable of x264 to test
 #
 # OPTIONS:
-# -t,--test --- the specific test to run
-#
-#               default: run all tests and print the number of tests
-#                        which passed.  If this is neutral, then exit
-#                        with 0.
-#
-# -l,--limit -- optionally specify limit script
-#
-#               default: use the limit located next to this script
+# -i,--input -- input file (default data/eledream_640x360_8.y4m)
+# -d,--decode - run the decode test as well
+# -p,--perf --- return profiling information gathered with linux perf
 #
 BASE="$(dirname $0)"
-TEST=""
-LIMIT="$BASE/limit"
-declare -a INPUTS
-declare -a OUTPUTS
+DECODE=""
+PERF=""
+RETURN=0
+if [ -z "$LIMIT" ];then LIMIT="${BASE}/limit"; fi
 HELP_TEXT=$(cat "$0" \
         |sed '/^[^#]/q' \
         |head -n -1 \
@@ -30,14 +27,15 @@ if [ $(grep "\-h" <(echo "$1")) ];then echo "$HELP_TEXT"; exit 0; fi
 PROG="$(dirname $1)/$(basename $1)"; shift;
 INPUT="$BASE/../data/eledream_640x360_8.y4m"
 
-eval set -- $(getopt -o ht:l: -l help,test:,limit: -- "$@" \
+eval set -- $(getopt -o hi:dp -l help,input:,decode,perf -- "$@" \
               || echo "$HELP_TEXT" && exit 1;)
 
 while [ $# -gt 0 ];do
     case $1 in
-        -h|--help)  echo "$HELP_TEXT" && exit 0;;
-        -t|--test)  TEST="$2"; shift;;
-        -l|--limit) LIMIT="$2"; shift;;
+        -h|--help)   echo "$HELP_TEXT" && exit 0;;
+        -i|--input)  INPUT="$2"; shift;;
+        -d|--decode) DECODE="yes";;
+        -p|--perf)   PERF="yes";;
         (--) shift; break;;
         (-*) error "unrecognized option $1";;
         (*)  break;;
@@ -50,33 +48,61 @@ FLAGS+=' --quiet --qp 20 --partitions b8x8,i4x4 --ref 5 --direct auto'
 FLAGS+=' --b-pyramid --weightb --mixed-refs --no-fast-pskip --me umh'
 FLAGS+=' --subme 7 --analyse b8x8,i4x4 --threads 1'
 
+OUTPUT=""
+OUTPUT+="Stream #0:0: Video: h264 (Main), yuv420p, 640x360, "
+OUTPUT+="25 fps, 25 tbr, 1200k tbn, 50 tbc"
+
+CMD='OFS="," {print $2,$1}'
+
+interpret_return(){ if [ -z "$1" ];then echo 0;else echo 1; fi; }
+
 run(){
-    
-    case $1 in
-        0)  # encoding of the normal file
-            local file=$(mktemp)
-            sh -c "$LIMIT $PROG $FLAGS -o $file $INPUT >/dev/null 2>/dev/null"
-            INFO=$(ffprobe $file 2>&1|grep Stream)
-            rm $file
-            diff -w <(echo "$INFO") \
-                    <(echo "Stream #0:0: Video: h264 (Main), yuv420p, 640x360, 25 fps, 25 tbr, 1200k tbn, 50 tbc") \
-            >/dev/null 2>/dev/null;;
-        1)  # value printed to STDOUT
-            diff <($LIMIT $PROG $FLAGS -o /dev/null $INPUT 2>&1|grep -v PARSEC|head -1) \
-                 <(echo "yuv4mpeg: 640x360@25/1fps, 0:0") \
-                 >/dev/null 2>/dev/null
-            ;;
-    esac; }
+    if [ ! -z "$PERF" ];then
+        local perf=$(mktemp)
+        $LIMIT perf stat -x, -o $perf -- $PROG $FLAGS $@ 1>/dev/null
+        RETURN=$?
+        if [ "$PERF" = "yes" ];then
+            PERF=$(cat $perf|tail -n +3)
+        else
+            PERF=$(join -t , \
+                <(echo "$PERF"|awk -F , $CMD) <(cat $perf|awk -F , $CMD) \
+                |awk -F , 'OFS="," {print ($2 + $3), $1}')
+        fi
+    else
+        $LIMIT $PROG $FLAGS $@ >/dev/null 2>/dev/null
+        RETURN=$?
+    fi;
+    return $RETURN; }
+
+encode(){
+    local file=$(mktemp)
+    if run -o $file $INPUT >/dev/null 2>/dev/null;then
+        INFO=$(ffprobe $file 2>&1|grep Stream)
+        rm -f $file
+        diff -w <(echo "$INFO") <(echo "$OUTPUT") >/dev/null 2>/dev/null;
+    else
+        echo "returned failure" >&2
+    fi; }
+
+decode(){
+    diff \
+        <($LIMIT $PROG $FLAGS -o /dev/null $INPUT 2>&1|grep -v PARSEC|head -1) \
+        <(echo "yuv4mpeg: 640x360@25/1fps, 0:0") \
+        >/dev/null 2>/dev/null; }
 
 # Actually run
-if [ -z "$TEST" ];then
-    count=0
-    for i in $(seq 0 1);do
-        if $(run $i);then count=$(($count + 1));fi
-    done
-    echo "$count"
-    exit 0
+if encode;then
+    if [ -z "$DECODE" ];then
+        if [ ! -z "$PERF" ];then echo "$PERF";fi
+        exit 0
+    else
+        if decode;then
+            if [ ! -z "$PERF" ];then echo "$PERF";fi
+            exit 0
+        else
+            exit 1
+        fi
+    fi
 else
-    if $(run $TEST);then exit 0;fi
+    exit 1
 fi
-exit 1
